### ISSUE TITLE
tag names

### ISSUE THREAD

**Issue by IzzySoft** [xarantolus/backtap#2]
Would it be possible to use the `version` (or the `versionCode`) for tag names, instead of the commit hash, so that they can be matched with `module.prop`? That would make it possible to automatically match and download a new release by simply checking against `module.prop`. And of course it would be totally fine to start that with the latest tag, no need to go back to older versions.

Thanks in advance!

**Comment by xarantolus** [comment]
Sure, makes sense. I honestly wasn't aware anyone else was using the pre-packaged builds as I thought it's quite specific to the ROM used, so interesting to hear :)

**Comment by IzzySoft** [comment]
To give you some background: I'm maintaining a [repo for FOSS modules](https://apt.izzysoft.de/magisk), currently serving 58 modules and counting. With the "official repos" serving a mix of FOSS and non-FOSS modules, mine is intended for those having a strong focus on FOSS (like me) and rather avoid non-FOSS parts – so they don't have to watch out what's FOSS and what's not, but can concentrate on what the modules achieve.

Backtap is definitely missing in my repo. Sounds quite convenient. One of my devices has a FPR on its back, so I'll most likely give it a try myself :smiley: Whether it's specific to the ROM I have not considered, TBH. Guess I've read it only mentions that it has been tested with a single ROM, which doesn't mean it wouldn't work with others. Well, we'll find out I guess? Once it becomes wider available and easy to find, more users might give it a try.

Please let me know when the latest version has a matching tag name (no need to re-tag older ones), so I'll pick up your module and configure it with my repo. Updates would then be fetched automatically (currently triggered manually a couple of times a week, but once things go stable on my end I'll most likely include it with the daily update check job for my F-Droid repo).

**Comment by xarantolus** [comment]
> repo for FOSS modules

That's really cool! I've been using your F-Droid repo for quite some time now and having one for FOSS modules is super nice! :)

> I'll most likely give it a try myself

Good luck, but tbh I don't really expect it to work out of the box (the paths for writing the fingerprint tap info seem to change with almost every OS version, and I'm not even sure if they stay the same across different devices or ROMs. Everything else should work though, so changing the paths might do the trick). 

> when the latest version has a matching tag name 

Now :)

---

BTW I really like the idea of your repo, good luck with it! Already added it to MRepo :D

**Comment by IzzySoft** [comment]
> That's really cool! I've been using your F-Droid repo for quite some time now and having one for FOSS modules is super nice! :)

Glad you like the idea :smiley:

> the paths for writing the fingerprint tap info seem to change with almost every OS version

Do you think it would be possible using a guide and some config page, that one could try adjusting it to one's own device?

> Now :)

Yeah! Let me echo that :partying_face:

> BTW I really like the idea of your repo, good luck with it! Already added it to MRepo :D

Cool, please refresh the list for module number 59 :smiley:

Thanks a lot! As the issue is solved, let's close it. Should questions come up, be welcome to ask. Listings with MRepo etc. should get more detailed with some future versions, Sanmer is working hard to get the issues closed while I'm opening new ones (currently, I'm faster – but I'm confident he'll catch up one day :see_no_evil:)
